/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20TokenContract } from "./ERC20TokenContract";
export * as factories from "./factories";
export { ERC20TokenContract__factory } from "./factories/ERC20TokenContract__factory";
